#!/usr/bin/env ruby

require "test_boosters/cucumber_booster"

cli_options = Semaphore::parse
thread_index = cli_options[:index] - 1
cucumber_booster = Semaphore::CucumberBooster.new(thread_index)
exit_status = cucumber_booster.run
exit(exit_status)
