#!/usr/bin/env ruby

require "test_boosters"

cli_options = TestBoosters::CliParser.parse
thread_index = cli_options[:index] - 1
cucumber_booster = TestBoosters::Cucumber::Booster.new(thread_index)

exit(cucumber_booster.run)
