#!/usr/bin/env ruby

require "test_boosters"

TestBoosters.run_cucumber_config

cli_options = TestBoosters::CliParser.parse
thread_index = cli_options[:index] - 1
cucumber_booster = TestBoosters::CucumberBooster.new(thread_index)

exit(cucumber_booster.run)
