#!/usr/bin/env ruby

require "test_boosters"

cli_options = TestBoosters::CliParser.parse

thread_index = cli_options[:index] - 1
thread_count = cli_options[:thread_count]

cucumber_booster = TestBoosters::Cucumber::Booster.new(thread_index, thread_count)

exit(cucumber_booster.run)
