#!/usr/bin/env ruby

require "test_boosters"

cli_options = TestBoosters::CliParser.parse

job_index = cli_options[:job_index] - 1
job_count = cli_options[:job_count]

rspec_booster = TestBoosters::Rspec::Booster.new(job_index, job_count)

exit(rspec_booster.run)
