#!/usr/bin/env ruby

require "test_boosters"

cli_options = TestBoosters.parse
thread_index = cli_options[:index] - 1
rspec_booster = TestBoosters::RspecBooster.new(thread_index)
exit_status = rspec_booster.run

report_path = rspec_booster.report_path
TestBoosters::InsightsUploader.new.upload("rspec", report_path)

exit(exit_status)
